[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "src/data/articles/*.md",
    "src/data/blog/*.md",
    "src/data/books/*.md"
  ]
